name: Build
on: 
  push: 
    branches:  [main]
  pull_request: 
    branches:  [main]
  workflow_dispatch:
jobs: 
  Build: 
    name: Build
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
      RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
    timeout-minutes: 360
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Build
      id: build-paclet-step
      uses: rhennigan/build-paclet@v1.7.1
      with: 
        target: Submit
        paclet_cicd_version: 0.16.1
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0
    - name: UploadArtifact
      id: upload-build-artifacts-step
      uses: actions/upload-artifact@v2
      with: 
        path: ${{ env.PACLET_BUILD_DIR }}
        if-no-files-found: error