name: Check
on: 
  push: 
    branches:  [main]
  pull_request: 
    branches:  [main]
  workflow_dispatch:
jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Check
      id: check-paclet-step
      uses: rhennigan/check-paclet@v1.4.0
      with: 
        target: Submit
        paclet_cicd_version: 0.10.1
        definition_notebook: ./DefinitionNotebook.nb