name: ReleaseWorkflow
on: 
  push: 
    branches:  [release/*]
jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    timeout-minutes: 10
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Check
      id: check-paclet-step
      uses: rhennigan/check-paclet@v1.4.0
      with: 
        target: Submit
        paclet_cicd_version: 0.9.0
        definition_notebook: ./DefinitionNotebook.nb
  Test: 
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    timeout-minutes: 10
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Test
      id: test-paclet-step
      uses: rhennigan/test-paclet@v1.0.0
      with: 
        target: Submit
        paclet_cicd_version: 0.9.0
        definition_notebook: ./DefinitionNotebook.nb
  Release: 
    needs:  [Check, Test]
    name: Release
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    timeout-minutes: 10
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Build
      id: build-paclet-step
      uses: rhennigan/build-paclet@v1.4.0
      with: 
        target: Submit
        paclet_cicd_version: 0.9.0
        definition_notebook: ./DefinitionNotebook.nb
    - name: UploadArtifact
      id: upload-build-artifacts-step
      uses: actions/upload-artifact@v2
      with: 
        path: ${{ env.BUILD_DIR }}
        if-no-files-found: error
    - name: CreateRelease
      id: create-release-step
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false
    - name: UploadRelease
      id: upload-release-asset-step
      uses: actions/upload-release-asset@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        upload_url: ${{ steps.create-release-step.outputs.upload_url }}
        asset_path: ${{ env.PACLET_PATH }}
        asset_name: ${{ env.PACLET_FILE }}
        asset_content_type: application/zip